services:
  redis:
    image: redis:7.0-alpine
    restart: always
    networks:
      - showping-net
    deploy:
      resources:
        limits:
          memory: 64M

  # MongoDB 서비스 추가
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    networks:
      - showping-net
    deploy:
      resources:
        limits:
          memory: 256M

  zookeeper:
    image: bitnamilegacy/zookeeper:3.9.3-debian-12-r22
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - showping-net
    deploy:
      resources:
        limits:
          memory: 128M

  kafka:
    image: bitnamilegacy/kafka:3.9.0
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - showping-net
    deploy:
      resources:
        limits:
          memory: 256M

  kms:
    image: kurento/kurento-media-server:latest
    restart: always
    ports:
      - "8888:8888"
    networks:
      - showping-net
    deploy:
      resources:
        limits:
          memory: 256M

  showping:
    image: ${DOCKER_USERNAME}/showping:latest
    restart: always
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - redis
      - mongo # mongo 의존성 추가
      - kafka
      - kms
    volumes:
      - /home/ec2-user/video:/app/video
    networks:
      - showping-net
    deploy:
      resources:
        limits:
          memory: 300M

networks:
  showping-net:
    driver: bridge